### ISSUE TITLE
imppg-1.9.0 won't install under Ubuntu-22.04

### ISSUE THREAD

**Issue by sophisticatedDreamer** [GreatAttractor/imppg#17]
Hello all,

imppg-1.9.0-Ubuntu_**20.04**.deb won't install under Ubuntu-**22.04** due to it's dependency on *libglew2.1*. Ubuntu**22.04** has *libglew2.2* installed and it seems that the previous version is not anymore available. I see 2 options:

A: Is there a workaround (e.g. fake symlinking *libglew2.2* to *libglew2.1*) so that **imppg** can be installed and used?

B: Will the recently published **imppg-1.9.0** will become available for Ubuntu-**22.04** (LTS aka long term support) any time soon?

I started loving **imppg** a while ago and have processed and published many Sun and Moon images (eg. on AstroBin) since, with impressive quality. Currently I am lost, having made the urgent system update from Ubuntu-20.04 to Ubuntu-22.04 because of other dependencies from different programs.

I want **imppg** back so bad! :) :)

**Comment by GreatAttractor** [comment]
ImPPG v. 1.9.1-beta has been published ([link](https://github.com/GreatAttractor/imppg/releases/tag/v1.9.1-beta)) — including an Ubuntu 22.04 package.

**Comment by sophisticatedDreamer** [comment]
Woaaaah! You are fast!!! Thanks a million times to bring (me) back this wonderful program! I shot the Sun yesterday und today at noon and feared I could not easily and as nicely process my data without **ImPPG**.

Installs and starts without issues ... great!

**Comment by GreatAttractor** [comment]
Good to hear that, have fun imaging!
