### ISSUE TITLE
Up/down buttons accept only one click

### ISSUE THREAD

**Issue by YiuXhu** [GreatAttractor/imppg#18]
Using the 1.9.1.beta version, the up/down buttons for 'Sigma' and 'Amount' only accept one mouseclick and then freeze. The value can change from 1,3000 to 1,2500 or 1,3500 and that's it. No further changes are accepted. The numerical value however can be changed freely by direct input via keyboard.

**Comment by GreatAttractor** [comment]
The fix will be included in the next version.

**Comment by YiuXhu** [comment]
Thank you Filip,

 

Kind regards, Theo

 

Van: Filip Szczerek ***@***.*** 
Verzonden: donderdag 13 juli 2023 13:19
Aan: GreatAttractor/imppg ***@***.***>
CC: YiuXhu ***@***.***>; Author ***@***.***>
Onderwerp: Re: [GreatAttractor/imppg] Up/down buttons accept only one click (Issue #18)

 

The fix will be included in the next version.
