### ISSUE TITLE
Crash when doing Image alignment

### ISSUE THREAD

**Issue by Blanshan91** [GreatAttractor/imppg#20]
I installed the latest version of ImPPG and I am trying to do image alignment on a set if TIFF files but when it does it crashes.  I tried in both CPU and GPU modes.  I am running latest Windows version and have a fast PC with GTX 3080 card.   Are there memory limits or something causing the crash?  Each TIFF file is only 1.2mb and I have 82 images.   Please let me know if you can help.  Thanks!!

Bill

**Comment by Blanshan91** [comment]
Ok I figured out the bug  I ran 0.6.5 version and I got an error when running "align on Solar limb" but when running on Beta I get no error and then it crashes.   When I run beta using "Stabilize high-constrast features" it works fine.

**Comment by GreatAttractor** [comment]
Could you upload the images somewhere for me to test (e.g., via DropBox, file.io)? Would be great if you can narrow the crash down to a smaller subset of them.

**Comment by Blanshan91** [comment]
Here is some data to test with: https://drive.google.com/file/d/1R2kbiyac0b4gf8f1t5e4uOpt-78o9dVr/view?usp=sharing

**Comment by GreatAttractor** [comment]
The fix will be included in the next version. Note that in case of these frames limb alignment doesn't work perfectly (the disc still shifts a bit), likely because of the large prominence.
