### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by naixx** [GreatAttractor/imppg#25]
I got a silent crash during solar alignment

1. Provide images of slightly different resolutions, even two images is enough
2. Select a `align on solar limb`
3. Get a crash

1.9.1-beta

**Comment by naixx** [comment]
[AS_P5.ZIP](https://github.com/user-attachments/files/16060145/AS_P5.ZIP)
@GreatAttractor sure. Crashes on solar lib option.

**Comment by GreatAttractor** [comment]
Confirmed as fixed on `master`. I'll release a new version soon.

**Comment by naixx** [comment]
It's working, thanks!
